//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using bottlenoselabs.C2CS.Runtime;
using GodotSharpGDExtension;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace GDExtension
{
	using System.Runtime.InteropServices;

	public static unsafe class Native
	{
		public static void asdads()
		{
			//classdb_register_extension_class
			GodotSharpGDExtension.GDExtension.cal
			// GodotSharpGDExtension.GDExtension.li
		}
	}
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
