[package]
name = "fsx_script"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.2.1", features = [ "api-custom", "experimental-threads"] }
lazy_static = { version = "1.5.0", features = [] }