[package]
name = "fsx_script"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["editor"]
template = ["godot/lazy-function-tables"]
editor = ["godot/experimental-threads"]

[dependencies]
godot = { version = "0.2.1", features = [ "api-custom"] }