[package]
name = "fsx_script"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
netcorehost = "0.17.0"
godot = { version = "0.1.2", features = ["api-custom", "experimental-threads"] }
log = "0.4.22"

[build-dependencies]
godot-bindings = { version = "0.1.2"}
