<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="ScriptSession.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GodotSharp" Version="4.4.0-beta.2" />
        <PackageReference Include="FSharp.Compiler.Service" Version="43.9.101"/>
        <PackageReference Include="FSharpx.Collections" Version="3.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Godot.FsxScript\Godot.FsxScript.fsproj"/>
    </ItemGroup>

</Project>
